### ISSUE TITLE
Kernel structure and its role in day to day

### ISSUE THREAD

**Issue by hilafish** [nukemberg/15m-ops-break#30]
Hi :)
Would love it if you could create an episode about kernel structure, and how knowing it can help incorporate it in day to day tasks and troubleshooting :)

**Comment by nukemberg** [comment]
ref #20 is this what you meant?

**Comment by hilafish** [comment]
yeah. if there's anything else important that is in this scope and you didn't mention there, then.. mention :)
other than that, closing this issue.
